version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:8.0
      volumes:
        - mysql_data:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: apicatalogo
        MYSQL_USER: user
        MYSQL_PASSWORD: 123456